# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bytedance/cocoapods_sdk_source_repo.git'

# GDT 需要：File - Workspace Setting，把切换到 Legacy Build System
target 'Unity-iPhone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Unity-iPhone

  target 'Unity-iPhone Tests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'UnityFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnityFramework

  # ModooPlay
  pod 'TGCenter'
  
  # Umeng
  pod 'TGCUmeng'
  
  # AppsFlyer
  pod 'TGCAppsFlyer'
  
  # 深度转化
  pod 'TGCRangersAppLog'
  pod 'RangersAppLog', '5.4.2',:subspecs => ['Core','Log','Unique']

  # 广告聚合
#  pod 'TGCTaurusXAds'
  # 穿山甲
  pod 'TaurusXAdMediation_TikTok'
  # 优量汇
  pod 'TaurusXAdMediation_GDT'
  # 快手
  pod 'TaurusXAdMediation_KuaiShou'
  # Mobrain
  pod 'TaurusXAdMediation_Mobrain'
  pod 'TaurusXAd_Mobrain_TikTok'
  pod 'TaurusXAdMediation_TikTok'
  pod 'TaurusXAd_Mobrain_GDT'
  pod 'TaurusXAdMediation_GDT'
  pod 'TaurusXAd_Mobrain_KuaiShou'
  pod 'TaurusXAdMediation_KuaiShou'
  
end
